/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BadkamersRouteImport } from './routes/badkamers'
import { Route as IndexRouteImport } from './routes/index'

const BadkamersRoute = BadkamersRouteImport.update({
  id: '/badkamers',
  path: '/badkamers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badkamers': typeof BadkamersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badkamers': typeof BadkamersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badkamers': typeof BadkamersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badkamers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badkamers'
  id: '__root__' | '/' | '/badkamers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadkamersRoute: typeof BadkamersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/badkamers': {
      id: '/badkamers'
      path: '/badkamers'
      fullPath: '/badkamers'
      preLoaderRoute: typeof BadkamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadkamersRoute: BadkamersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
