/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealisatiesRouteImport } from './routes/realisaties'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as KeukensRouteImport } from './routes/keukens'
import { Route as DressingsRouteImport } from './routes/dressings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BadkamersRouteImport } from './routes/badkamers'
import { Route as AanpakRouteImport } from './routes/aanpak'
import { Route as IndexRouteImport } from './routes/index'

const RealisatiesRoute = RealisatiesRouteImport.update({
  id: '/realisaties',
  path: '/realisaties',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const KeukensRoute = KeukensRouteImport.update({
  id: '/keukens',
  path: '/keukens',
  getParentRoute: () => rootRouteImport,
} as any)
const DressingsRoute = DressingsRouteImport.update({
  id: '/dressings',
  path: '/dressings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BadkamersRoute = BadkamersRouteImport.update({
  id: '/badkamers',
  path: '/badkamers',
  getParentRoute: () => rootRouteImport,
} as any)
const AanpakRoute = AanpakRouteImport.update({
  id: '/aanpak',
  path: '/aanpak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/contact': typeof ContactRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/contact': typeof ContactRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/contact': typeof ContactRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanpak'
    | '/badkamers'
    | '/contact'
    | '/dressings'
    | '/keukens'
    | '/over-ons'
    | '/realisaties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanpak'
    | '/badkamers'
    | '/contact'
    | '/dressings'
    | '/keukens'
    | '/over-ons'
    | '/realisaties'
  id:
    | '__root__'
    | '/'
    | '/aanpak'
    | '/badkamers'
    | '/contact'
    | '/dressings'
    | '/keukens'
    | '/over-ons'
    | '/realisaties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanpakRoute: typeof AanpakRoute
  BadkamersRoute: typeof BadkamersRoute
  ContactRoute: typeof ContactRoute
  DressingsRoute: typeof DressingsRoute
  KeukensRoute: typeof KeukensRoute
  OverOnsRoute: typeof OverOnsRoute
  RealisatiesRoute: typeof RealisatiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realisaties': {
      id: '/realisaties'
      path: '/realisaties'
      fullPath: '/realisaties'
      preLoaderRoute: typeof RealisatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keukens': {
      id: '/keukens'
      path: '/keukens'
      fullPath: '/keukens'
      preLoaderRoute: typeof KeukensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dressings': {
      id: '/dressings'
      path: '/dressings'
      fullPath: '/dressings'
      preLoaderRoute: typeof DressingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badkamers': {
      id: '/badkamers'
      path: '/badkamers'
      fullPath: '/badkamers'
      preLoaderRoute: typeof BadkamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanpak': {
      id: '/aanpak'
      path: '/aanpak'
      fullPath: '/aanpak'
      preLoaderRoute: typeof AanpakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanpakRoute: AanpakRoute,
  BadkamersRoute: BadkamersRoute,
  ContactRoute: ContactRoute,
  DressingsRoute: DressingsRoute,
  KeukensRoute: KeukensRoute,
  OverOnsRoute: OverOnsRoute,
  RealisatiesRoute: RealisatiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
