/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KeukensRouteImport } from './routes/keukens'
import { Route as DressingsRouteImport } from './routes/dressings'
import { Route as BadkamersRouteImport } from './routes/badkamers'
import { Route as AanpakRouteImport } from './routes/aanpak'
import { Route as IndexRouteImport } from './routes/index'

const KeukensRoute = KeukensRouteImport.update({
  id: '/keukens',
  path: '/keukens',
  getParentRoute: () => rootRouteImport,
} as any)
const DressingsRoute = DressingsRouteImport.update({
  id: '/dressings',
  path: '/dressings',
  getParentRoute: () => rootRouteImport,
} as any)
const BadkamersRoute = BadkamersRouteImport.update({
  id: '/badkamers',
  path: '/badkamers',
  getParentRoute: () => rootRouteImport,
} as any)
const AanpakRoute = AanpakRouteImport.update({
  id: '/aanpak',
  path: '/aanpak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/badkamers': typeof BadkamersRoute
  '/dressings': typeof DressingsRoute
  '/keukens': typeof KeukensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aanpak' | '/badkamers' | '/dressings' | '/keukens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aanpak' | '/badkamers' | '/dressings' | '/keukens'
  id: '__root__' | '/' | '/aanpak' | '/badkamers' | '/dressings' | '/keukens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanpakRoute: typeof AanpakRoute
  BadkamersRoute: typeof BadkamersRoute
  DressingsRoute: typeof DressingsRoute
  KeukensRoute: typeof KeukensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/keukens': {
      id: '/keukens'
      path: '/keukens'
      fullPath: '/keukens'
      preLoaderRoute: typeof KeukensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dressings': {
      id: '/dressings'
      path: '/dressings'
      fullPath: '/dressings'
      preLoaderRoute: typeof DressingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badkamers': {
      id: '/badkamers'
      path: '/badkamers'
      fullPath: '/badkamers'
      preLoaderRoute: typeof BadkamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanpak': {
      id: '/aanpak'
      path: '/aanpak'
      fullPath: '/aanpak'
      preLoaderRoute: typeof AanpakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanpakRoute: AanpakRoute,
  BadkamersRoute: BadkamersRoute,
  DressingsRoute: DressingsRoute,
  KeukensRoute: KeukensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
